### ISSUE TITLE
Layout improvements

### ISSUE THREAD

**Issue by samreid** [phetsims/sound#10]
While reviewing the sim, I saw the layout looks like this:

<img width="1191" alt="image" src="https://user-images.githubusercontent.com/679486/202833924-cbe43312-6217-4ca9-8e6b-105a00fca1f1.png">

This seems unbalanced, can we please try the following?
1. Move the play/pause buttons to the right, under the control panels
2. Scale the sound box (maintaining aspect ratio) so that it fills the dev bounds vertically
3. Left-align the sound box with the left edge of the dev bounds
4. Make the control panel fonts and controls larger
5. For the control panel and reset all button, use the same margin on the top/right/bottom edges

**Comment by arouinfar** [comment]
This sim is not currently a priority, so unassigning myself.

**Comment by samreid** [comment]
@matthew-blackman centered the sound area, and we agreed it seems an appropriate design for this publication. Closing.
