### ISSUE TITLE
Check that all features of the legacy java sim are carried over

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/sound#24]
The sim is looking very close to feature complete. All features from the java sim appear to be implemented, with the following intentional changes:

- Removed the "cone effect" from the sound waves coming out of the speaker
- Add 'x' symbol to person in Two Sources screen to show the location being sonified
- Limit dragging of person to the vertical axis in Two Sources screen
- Changed the UX from 'Air Density in Speaker Box' from an on/off button to a slider

@KatieWoe can you check that all features are correctly carried over from the java version, other than the intentional differences listed above?

**Comment by KatieWoe** [comment]
There is no longer a 'clear wave" button on the measure screen.

**Comment by matthew-blackman** [comment]
I am seeing the 'Clear Waves' button below the Amplitude slider. Can you confirm? I will move it to the same location as the java sim.

**Comment by KatieWoe** [comment]
You are correct. Sorry about that

**Comment by matthew-blackman** [comment]
No worries! Good find - the button looks much better in the new location. I also updated the screen icons to remove the "cone effect" on the waves.

**Comment by KatieWoe** [comment]
Looks feature complete on main to me.
