### ISSUE TITLE
Replace the Java version of the "Sound" sim

### ISSUE THREAD

**Issue by samreid** [phetsims/sound#4]
It would be nice to replace the Java version of the Sound sim.  We did not port sound to "decaf" via CheerpJ due to incompatibilities with the sound output.

I published a dev version here for review: https://phet-dev.colorado.edu/html/sound/1.0.0-dev.2/phet/sound_en_phet.html

What else would need to be done before this can replace the Java version?

**Comment by arouinfar** [comment]
This sim is not currently a priority, so unassigning myself.
