### ISSUE TITLE
Locate Dutch Strings? 

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/sound#7]
I tried to run the all version here in Dutch, and it didn't load. I believe the Dutch strings were provided. Not sure how they can be extracted and used within our system, or if we will just have to redo them after publication. 
https://phet-dev.colorado.edu/html/sound/1.0.0-dev.2/phet/sound_all_phet.html?locale=nl

**Comment by samreid** [comment]
@jbphet commented on how this might be accomplished in https://github.com/phetsims/sound/issues/5, closing as duplicate
