### ISSUE TITLE
Screen names are a bit long

### ISSUE THREAD

**Issue by samreid** [phetsims/sound#8]
Navbar looks like this:

<img width="987" alt="image" src="https://user-images.githubusercontent.com/679486/198842456-611e10cb-b79d-4878-8d9b-6d82509bdc4a.png">

**Comment by samreid** [comment]
I pruned them a bit in this commit:

<img width="988" alt="image" src="https://user-images.githubusercontent.com/679486/198842554-c6405168-0dee-4b14-8b09-3d77e076e664.png">

**Comment by arouinfar** [comment]
Thanks @samreid. The updated screen names look good to me.
